#!/usr/bin/env node
// Copy the repo's canonical results into the package's bundled data/ dir so
// the published npx server ships its data. Run before publish and in the
// remote app build.
import { readdirSync, mkdirSync, copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const resultsDir = resolve(here, "../../results");
const outDir = resolve(here, "../data");
mkdirSync(outDir, { recursive: true });
const docs = [];
let n = 0;
if (existsSync(resultsDir)) {
  for (const f of readdirSync(resultsDir)) {
    if (f.endsWith(".json") && f !== "index.json") {
      copyFileSync(join(resultsDir, f), join(outDir, f));
      docs.push(JSON.parse(readFileSync(join(resultsDir, f), "utf8")));
      n++;
    }
  }
}

// Also inline the canonical docs into a JS module. Vercel's serverless file
// tracing does not reliably bundle a fs-read data/ dir, so the remote endpoint
// reads this statically-imported module instead; the stdio/npx server keeps the
// fs fallback. Committed so the build always has it before next build runs.
const modulePath = resolve(here, "../src/bundled-data.js");
writeFileSync(
  modulePath,
  "// AUTO-GENERATED by scripts/sync-data.mjs. Do not edit by hand.\n" +
    "// Regenerate with `npm run sync:data`.\n" +
    `export const BUNDLED_DOCS = ${JSON.stringify(docs)};\n`
);
console.log(`sync-data: bundled ${n} canonical result file(s) into data/ and src/bundled-data.js`);
