#!/usr/bin/env node
// Copy the repo's canonical results into the package's bundled data/ dir so
// the published npx server ships its data. Run before publish and in the
// remote app build.
import { readdirSync, mkdirSync, copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const resultsDir = resolve(here, "../../results");
const outDir = resolve(here, "../data");
mkdirSync(outDir, { recursive: true });

// Refresh data/ from the repo results/ when it is present (local dev). On the
// Vercel build the repo results/ is not in the build context, so data/ keeps
// its committed contents and this copy step is simply a no-op.
let copied = 0;
if (existsSync(resultsDir)) {
  for (const f of readdirSync(resultsDir)) {
    if (f.endsWith(".json") && f !== "index.json") {
      copyFileSync(join(resultsDir, f), join(outDir, f));
      copied++;
    }
  }
}

// Inline whatever ended up in data/ into a JS module. Vercel's serverless file
// tracing does not reliably bundle an fs-read data/ dir, so the remote endpoint
// imports this module statically instead. Sourcing from data/ (not results/)
// means the committed data survives a build that has no repo results/.
// Copy the sourced pricing into the committed data/ dir (local dev), then read
// it from there. On the Vercel build the repo docs/ is absent, so data/ keeps
// its committed pricing.json and the cost fields survive. Excluded from the
// docs glob below so it is never parsed as a result doc.
const pricingSrc = resolve(here, "../../docs/pricing.json");
const pricingDst = join(outDir, "pricing.json");
if (existsSync(pricingSrc)) copyFileSync(pricingSrc, pricingDst);

const docs = readdirSync(outDir)
  .filter((f) => f.endsWith(".json") && f !== "index.json" && f !== "pricing.json")
  .map((f) => JSON.parse(readFileSync(join(outDir, f), "utf8")));
const pricing = existsSync(pricingDst) ? JSON.parse(readFileSync(pricingDst, "utf8")) : null;
const modulePath = resolve(here, "../src/bundled-data.js");
writeFileSync(
  modulePath,
  "// AUTO-GENERATED by scripts/sync-data.mjs. Do not edit by hand.\n" +
    "// Regenerate with `npm run sync:data`.\n" +
    `export const BUNDLED_DOCS = ${JSON.stringify(docs)};\n` +
    `export const BUNDLED_PRICING = ${JSON.stringify(pricing)};\n`
);
console.log(
  `sync-data: copied ${copied} file(s) from results/, bundled ${docs.length} doc(s) + pricing into src/bundled-data.js`
);
